language: python

notifications:
  email: false

os:
  - linux

python:
  - "2.7"
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - py.test --cov-report=xml --cov

after_success:
  - codecov
